[package]
name = "dugong-mesh"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dugong-types = { path = "../types" }
thiserror = "2"
