[package]
name = "dugong-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
typenum = "1"

[dev-dependencies]
trybuild = "1"

[lib]
